# Additional sunxi build rules

CROSS_PREFIX ?= ../toolchain/xtensa-hifi4-gcc/bin/xtensa-hifi4-elf-

dirs-y += src/sunxi src/generic

src-y += sunxi/main.c
#src-y += sunxi/main.c sunxi/gpio.c sunxi/timer.c sunxi/serial.c
#src-y += generic/crc16_ccitt.c generic/alloc.c
#src-y += generic/timer_irq.c generic/serial_irq.c
